@startuml
node "User PC" {
    artifact "PoliticalSim.exe" {
        [MainWindow]
        [PartyModel]
        [VoterModel]
        [IdeologyModel]
        [AddPartyDialog]
        [AddVoterDialog]
        [ChartView]
    }

    database "politicalsim.sqlite" as SQLiteDB
}

[PartyModel] --> SQLiteDB
[VoterModel] --> SQLiteDB
[IdeologyModel] --> SQLiteDB
[MainWindow] --> [PartyModel]
[MainWindow] --> [VoterModel]
[MainWindow] --> [IdeologyModel]
[MainWindow] --> [ChartView]
[MainWindow] --> [AddPartyDialog]
[MainWindow] --> [AddVoterDialog]
@enduml
